export const START_GET_POSTS = "START_GET_POSTS";
export const SUCCESS_GET_POSTS = "SUCCESS_GET_POSTS";
export const ERROR_GET_POSTS = "ERROR_GET_POSTS";

export const START_CREATE_POSTS = "START_CREATE_POSTS";
export const SUCCESS_CREATE_POSTS = "SUCCESS_CREATE_POSTS";
export const ERROR_CREATE_POSTS = "ERROR_CREATE_POSTS";

export const START_DELETE_POSTS = "START_DELETE_POSTS";
export const SUCCESS_DELETE_POSTS = "SUCCESS_DELETE_POSTS";
export const ERROR_DELETE_POSTS = "ERROR_DELETE_POSTS";