export const START_LOGIN_USER = "START_LOGIN_USER";
export const SUCCESS_LOGIN_USER = "SUCCESS_LOGIN_USER";
export const ERROR_LOGIN_USER = "ERROR_LOGIN_USER";

export const START_CREATE_USER = "START_CREATE_USER";
export const SUCCESS_CREATE_USER = "SUCCESS_CREATE_USER";
export const ERROR_CREATE_USER = "ERROR_CREATE_USER";

export const START_CHECK_USER = "START_CHECK_USER";
export const SUCCESS_CHECK_USER = "SUCCESS_CHECK_USER";
export const ERROR_CHECK_USER = "ERROR_CHECK_USER";

export const START_LOGOUT_USER = "START_LOGOUT_USER";